import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        error: "#b02500",
        "surface-container-low": "#f0f1f1",
        "on-error": "#ffefec",
        "primary-fixed-dim": "#f46800",
        "on-surface-variant": "#5a5c5c",
        "on-primary": "#fff0ea",
        "on-secondary": "#fff0e8",
        "on-error-container": "#520c00",
        "primary-container": "#ff7a2c",
        "surface-container-highest": "#dbdddd",
        "on-tertiary": "#fff1df",
        "tertiary-fixed": "#f7b21f",
        "error-dim": "#b92902",
        "on-secondary-fixed": "#552800",
        "tertiary-fixed-dim": "#e7a407",
        "on-tertiary-container": "#4f3600",
        secondary: "#8f4800",
        "primary-dim": "#883700",
        "tertiary-dim": "#6b4900",
        "primary-fixed": "#ff7a2c",
        "error-container": "#f95630",
        "surface-tint": "#9b3f00",
        tertiary: "#7a5400",
        "on-background": "#2d2f2f",
        "on-primary-fixed": "#000000",
        "on-surface": "#2d2f2f",
        "surface-variant": "#dbdddd",
        surface: "#f6f6f6",
        "surface-container-lowest": "#ffffff",
        primary: "#9b3f00",
        "inverse-surface": "#0c0f0f",
        "on-secondary-fixed-variant": "#7f3f00",
        "surface-dim": "#d3d5d5",
        "secondary-fixed-dim": "#ffb37c",
        "on-tertiary-fixed": "#342200",
        "secondary-container": "#ffc69f",
        outline: "#767777",
        "surface-container-high": "#e1e3e3",
        "surface-bright": "#f6f6f6",
        "secondary-dim": "#7e3f00",
        "outline-variant": "#acadad",
        "on-secondary-container": "#713800",
        "secondary-fixed": "#ffc69f",
        "surface-container": "#e7e8e8",
        "on-tertiary-fixed-variant": "#5b3e00",
        background: "#f6f6f6",
        "tertiary-container": "#f7b21f",
        "inverse-on-surface": "#9c9d9d",
        "inverse-primary": "#fd6c00",
        "on-primary-fixed-variant": "#4f1d00",
        "on-primary-container": "#401600",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
    },
  },
  plugins: [],
};
export default config;
